#!/bin/bash
#$ -V             # Pass environment variables to the job
#$ -N run-merge    
#$ -cwd           # Use the current working dir		 
#$ -pe smp 1      # Parallel Environment (how many cores)
#$ -l h_vmem=2G   # Memory (RAM) allocation *per core*   

script_dir=`dirname "$(readlink -f "$0")"`

USAGE="qsub $(basename "$0") [-h] [-b|--barcode_id] -i|--input" 

if [[ ( $1 == "--help") ||  $1 == "-h" ]] 
then 
  echo "${USAGE}"
  exit 0
fi

INPUT=""
PASS_FAIL=""
BARCODE_ID=""

while [[ $# -gt 0 ]]
do
  key="$1"
  
  case $key in
    -i|--input)
    # Input directory
    INPUT="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
  esac
done

echo "[" `date --iso-8601=ns --utc` "]" "{ \"input_directory\":" "${input_dir}" "}"
echo "[" `date --iso-8601=ns --utc` "]" "{ \"output_directory\":" "${output_dir}" "}"
echo "[" `date --iso-8601=ns --utc` "]" "{ \"merged_fastq_filename\":" "${merged_fastq_filename}" "}"

# Run program
cat "${fastqs[@]}" > "${output_dir}"/"${merged_fastq_filename}"

