#!/bin/bash
#$ -V             # Pass environment variables to the job
#$ -N minimap2
#$ -cwd           # Use the current working dir		 
#$ -pe smp 8      # Parallel Environment (how many cores)
#$ -l h_vmem=2G   # Memory (RAM) allocation *per core*   

USAGE="qsub $(basename "$0") [-h] -r|--reference REFERENCE -f|--fastq FASTQ -o|--output OUTPUT" 

if [[ ( $1 == "--help") ||  $1 == "-h" ]] 
then 
  echo "${USAGE}"
  exit 0
fi

REFERENCE=""
FASTQ=""
MODE="map-ont"


while [[ $# -gt 0 ]]
do
  key="$1"
  
  case $key in
    -r|--reference)
    # Input directory
    REFERENCE="$2"
    shift # past argument
    shift # past value
    ;;
    -f|--fastq)
    # Output directory
    FASTQ="$2"
    shift # past argument
    shift # past value
    ;;
    -o|--output)
    # Output directory
    OUTPUT="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
  esac
done
# set -- "${POSITIONAL[@]}" # restore positional parameters

echo REFERENCE  = "${REFERENCE}"
echo FASTQ      = "${FASTQ}"
echo OUTPUT     = "${OUTPUT}"
# echo POSITIONAL = "${@}"

# Activate a conda environment if necessary
source /opt/miniconda2/bin/activate minimap2

# Run program
minimap2 -ax "${MODE}" "${REFERENCE}" "${FASTQ}" | samtools sort -@ 7 --reference "${REFERENCE}" -o "${OUTPUT}"
