#!/bin/bash
#$ -V             # Pass environment variables to the job
#$ -N np_index
#$ -cwd           # Use the current working dir		 
#$ -pe smp 8      # Parallel Environment (how many cores)
#$ -l h_vmem=2G   # Memory (RAM) allocation *per core*   

USAGE="qsub $(basename "$0") [-h] -5|--fast5 FAST5_DIR -q|--fastq FASTQ -s|--sequencing_summary SEQUENCING_SUMMARY" 

nanopolish_version="0.10.2"

if [[ ( $1 == "--help") ||  $1 == "-h" ]] 
then 
  echo "${USAGE}"
  exit 0
fi

fast5=""
fastq=""
sequencing_summary=""

while [[ $# -gt 0 ]]
do
  key="$1"
  
  case $key in
    -5|--fast5)
    # Parent directory containing sub-dirs with a fast5 directory
    FAST5="$2"
    shift # past argument
    shift # past value
    ;;
    -q|--fastq)
    # The merged fastq file to index
    FASTQ="$2"
    shift # past argument
    shift # past value
    ;;
    -s|--sequencing_summary)
    # The merged sequencing_summary.txt file
    sequencing_summary="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
  esac
done

echo "{ \"sequencing_summary\": "${sequencing_summary}" }"
echo "{ \"fast5\": "${fast5}" }"
echo "{ \"fastq\": "${fastq}" }"

# Activate a conda environment if necessary
source /opt/miniconda2/bin/activate nanopolish-"${nanopolish_version}"

# Run program
nanopolish index -s "${sequencing_summary}" -d "${fast5}" "${fastq}"
