#!/bin/bash
#$ -V             # Pass environment variables to the job
#$ -N fq-merge    
#$ -cwd           # Use the current working dir		 
#$ -pe smp 1      # Parallel Environment (how many cores)
#$ -l h_vmem=2G   # Memory (RAM) allocation *per core*   

USAGE="qsub $(basename "$0") [-h] -i|--input (-p|--pass | -f|--fail) [-b|--barcode_id]" 

if [[ ( $1 == "--help") ||  $1 == "-h" ]] 
then 
  echo "${USAGE}"
  exit 0
fi

INPUT=""
PASS_FAIL=""
BARCODE_ID=""

while [[ $# -gt 0 ]]
do
  key="$1"
  
  case $key in
    -i|--input)
    # Input directory
    INPUT="$2"
    shift # past argument
    shift # past value
    ;;
    -p|--pass)
    # Merge 'pass' reads
    PASS_FAIL="pass"
    shift # past argument
    ;;
    -f|--fail)
    # Merge 'fail' reads
    PASS_FAIL="fail"
    shift # past argument
    ;;
    -b|--barcode_id)
    # Run is barcoded
    BARCODE_ID="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
  esac
done

echo INPUT       = "${INPUT}"
echo PASS_FAIL   = "${PASS_FAIL}"
echo BARCODE_ID  = "${BARCODE_ID}"

# Activate a conda environment if necessary
# source /opt/miniconda2/bin/activate nanopore

# Run program
cat "${INPUT}"/fastq/*/workspace/"${PASS_FAIL}"/"${BARCODE_ID}"/*.fastq | bgzip > "${INPUT}"/merged/$( basename ${INPUT} )_"${BARCODE_ID}"."${PASS_FAIL}".merged.fastq.gz

