#!/bin/bash
#$ -V             # Pass environment variables to the job
#$ -N np_index
#$ -cwd           # Use the current working dir		 
#$ -pe smp 8      # Parallel Environment (how many cores)
#$ -l h_vmem=2G   # Memory (RAM) allocation *per core*   

USAGE="qsub $(basename "$0") [-h] -5|--fast5 FAST5_DIR -q|--fastq FASTQ" 

if [[ ( $1 == "--help") ||  $1 == "-h" ]] 
then 
  echo "${USAGE}"
  exit 0
fi

FAST5=""
FASTQ=""
POSITIONAL=()

while [[ $# -gt 0 ]]
do
  key="$1"
  
  case $key in
    -5|--fast5)
    # fast5 directory
    FAST5="$2"
    shift # past argument
    shift # past value
    ;;
    -q|--fastq)
    # The merged fastq file to index
    FASTQ="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
  esac
done

echo FAST5  = "${FAST5}"
echo FASTQ  = "${FASTQ}"

# Activate a conda environment if necessary
source /opt/miniconda2/bin/activate nanopore

# Run program
ls -1 $( dirname $( dirname $( dirname "${FASTQ}" ) ) )/fastq/*/sequencing_summary.txt | nanopolish index -d "${FAST5}" -f /dev/stdin "${FASTQ}"
